name: rudeshko.net - CICD

on:
  push:
    branches:
      - master

jobs:
  cicd:
    runs-on: ubuntu-18.04
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v1
      - name: Install NPM packages
        run: npm install
      - name: Build the project
        run: npm run build
      - name: Deploy to S3
        run: npm run deploy
